apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: phzgq2d7d-nodejs
  janus-idp.io/tekton: phzgq2d7d-nodejs
  backstage.io/kubernetes-id: phzgq2d7d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: phzgq2d7d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
